# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(1149, 862)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../.designer/backup/img/camara.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Window.setWindowIcon(icon)
        Window.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 100))
        self.groupBox.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonReproducir = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonReproducir.sizePolicy().hasHeightForWidth())
        self.pushButtonReproducir.setSizePolicy(sizePolicy)
        self.pushButtonReproducir.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("KacstQurn")
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonReproducir.setFont(font)
        self.pushButtonReproducir.setStyleSheet("background-color: rgb(163, 163, 163);")
        self.pushButtonReproducir.setAutoDefault(False)
        self.pushButtonReproducir.setObjectName("pushButtonReproducir")
        self.horizontalLayout.addWidget(self.pushButtonReproducir)
        self.panelAlineacion = QtWidgets.QGroupBox(self.groupBox)
        self.panelAlineacion.setStyleSheet("color: rgb(255, 255, 255);")
        self.panelAlineacion.setObjectName("panelAlineacion")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.panelAlineacion)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonVerticalIz = QtWidgets.QPushButton(self.panelAlineacion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonVerticalIz.sizePolicy().hasHeightForWidth())
        self.pushButtonVerticalIz.setSizePolicy(sizePolicy)
        self.pushButtonVerticalIz.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("KacstQurn")
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonVerticalIz.setFont(font)
        self.pushButtonVerticalIz.setStyleSheet("background-color: rgb(163, 163, 163);")
        self.pushButtonVerticalIz.setAutoDefault(False)
        self.pushButtonVerticalIz.setObjectName("pushButtonVerticalIz")
        self.horizontalLayout_2.addWidget(self.pushButtonVerticalIz)
        self.pushButtonVerticalDer = QtWidgets.QPushButton(self.panelAlineacion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonVerticalDer.sizePolicy().hasHeightForWidth())
        self.pushButtonVerticalDer.setSizePolicy(sizePolicy)
        self.pushButtonVerticalDer.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("KacstQurn")
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonVerticalDer.setFont(font)
        self.pushButtonVerticalDer.setStyleSheet("background-color: rgb(163, 163, 163);")
        self.pushButtonVerticalDer.setAutoDefault(False)
        self.pushButtonVerticalDer.setObjectName("pushButtonVerticalDer")
        self.horizontalLayout_2.addWidget(self.pushButtonVerticalDer)
        self.pushButtonBorrar = QtWidgets.QPushButton(self.panelAlineacion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBorrar.sizePolicy().hasHeightForWidth())
        self.pushButtonBorrar.setSizePolicy(sizePolicy)
        self.pushButtonBorrar.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("KacstQurn")
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonBorrar.setFont(font)
        self.pushButtonBorrar.setStyleSheet("background-color: rgb(163, 163, 163);")
        self.pushButtonBorrar.setAutoDefault(False)
        self.pushButtonBorrar.setObjectName("pushButtonBorrar")
        self.horizontalLayout_2.addWidget(self.pushButtonBorrar)
        self.pushButtonCalcularAlinea = QtWidgets.QPushButton(self.panelAlineacion)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCalcularAlinea.sizePolicy().hasHeightForWidth())
        self.pushButtonCalcularAlinea.setSizePolicy(sizePolicy)
        self.pushButtonCalcularAlinea.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("KacstQurn")
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonCalcularAlinea.setFont(font)
        self.pushButtonCalcularAlinea.setStyleSheet("background-color: rgb(163, 163, 163);")
        self.pushButtonCalcularAlinea.setAutoDefault(False)
        self.pushButtonCalcularAlinea.setObjectName("pushButtonCalcularAlinea")
        self.horizontalLayout_2.addWidget(self.pushButtonCalcularAlinea)
        self.horizontalLayout.addWidget(self.panelAlineacion)
        self.panelSuperficie = QtWidgets.QGroupBox(self.groupBox)
        self.panelSuperficie.setStyleSheet("color: rgb(255, 255, 255);")
        self.panelSuperficie.setObjectName("panelSuperficie")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.panelSuperficie)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonSelFondo = QtWidgets.QPushButton(self.panelSuperficie)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSelFondo.sizePolicy().hasHeightForWidth())
        self.pushButtonSelFondo.setSizePolicy(sizePolicy)
        self.pushButtonSelFondo.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("KacstQurn")
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSelFondo.setFont(font)
        self.pushButtonSelFondo.setStyleSheet("background-color: rgb(163, 163, 163);")
        self.pushButtonSelFondo.setAutoDefault(False)
        self.pushButtonSelFondo.setObjectName("pushButtonSelFondo")
        self.horizontalLayout_3.addWidget(self.pushButtonSelFondo)
        self.pushButtonCalcularFondo = QtWidgets.QPushButton(self.panelSuperficie)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCalcularFondo.sizePolicy().hasHeightForWidth())
        self.pushButtonCalcularFondo.setSizePolicy(sizePolicy)
        self.pushButtonCalcularFondo.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("KacstQurn")
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonCalcularFondo.setFont(font)
        self.pushButtonCalcularFondo.setStyleSheet("background-color: rgb(163, 163, 163);")
        self.pushButtonCalcularFondo.setAutoDefault(False)
        self.pushButtonCalcularFondo.setObjectName("pushButtonCalcularFondo")
        self.horizontalLayout_3.addWidget(self.pushButtonCalcularFondo)
        self.horizontalLayout.addWidget(self.panelSuperficie)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 2)
        self.panelDepth = QtWidgets.QGroupBox(self.centralwidget)
        self.panelDepth.setStyleSheet("color: rgb(255, 255, 255);")
        self.panelDepth.setObjectName("panelDepth")
        self.gridLayout.addWidget(self.panelDepth, 1, 1, 1, 1)
        self.panelRGB = QtWidgets.QGroupBox(self.centralwidget)
        self.panelRGB.setStyleSheet("color: rgb(255, 255, 255);")
        self.panelRGB.setObjectName("panelRGB")
        self.gridLayout.addWidget(self.panelRGB, 1, 0, 1, 1)
        Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1149, 20))
        self.menubar.setObjectName("menubar")
        Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Window)
        self.statusbar.setObjectName("statusbar")
        Window.setStatusBar(self.statusbar)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "MainWindow"))
        self.groupBox.setTitle(_translate("Window", "herramientas"))
        self.pushButtonReproducir.setText(_translate("Window", "Reproducir"))
        self.panelAlineacion.setTitle(_translate("Window", "Alineación"))
        self.pushButtonVerticalIz.setText(_translate("Window", "Vertical IZ"))
        self.pushButtonVerticalDer.setText(_translate("Window", "Vertical DER"))
        self.pushButtonBorrar.setText(_translate("Window", "Borrar"))
        self.pushButtonCalcularAlinea.setText(_translate("Window", "Calcular"))
        self.panelSuperficie.setTitle(_translate("Window", "Superficie"))
        self.pushButtonSelFondo.setText(_translate("Window", "Selec Fondo"))
        self.pushButtonCalcularFondo.setText(_translate("Window", "Calcular "))
        self.panelDepth.setTitle(_translate("Window", "Depth"))
        self.panelRGB.setTitle(_translate("Window", "RGB"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Window = QtWidgets.QMainWindow()
    ui = Ui_Window()
    ui.setupUi(Window)
    Window.show()
    sys.exit(app.exec_())

